/**
 * @file src/vr/vr_ipc_abi_table.h
 * @brief VipleStream §VR（M1b S1-06／S1-18，selftest T6）：vr_ipc_abi.h 的 sizeof／alignof／offsetof 對照表。
 *
 * server（MinGW GCC）與 vr_probe（MSVC）**include 同一份表**，各自以自己的編譯器算出數值後逐列印出，
 * selftest T6 逐字比對兩邊的輸出：任何一列不同，就代表兩個編譯器對同一份 ABI 的版面理解不同
 * （或 vr_probe 是以舊版標頭建出來的），IPC 不可上線。
 *
 * 列的格式固定為 `<key>=<十進位值>`，不含空白：
 *   - `const.<巨集>`：版號、magic、各種容量常數（抓「vr_probe 用了舊標頭」）
 *   - `size.<型別>`、`align.<型別>`：sizeof／alignof
 *   - `off.<型別>.<欄位>`：offsetof（每個欄位都列，包含 reserved／pad）
 * vr_probe 的輸出行：`[VIPLE-VR-PROBE] abi-row <key>=<value>`，最後一行
 * `[VIPLE-VR-PROBE] abi-rows count=<n> digest=<16 位十六進位>`（digest 見 table_digest()）。
 *
 * 規則：
 *   - 這份表由 vr_ipc_abi.h 機械產生（每個 typedef struct 的每個欄位）；ABI 加欄位時一起更新，
 *     漏列的欄位不會被比對到。
 *   - 只依賴標準函式庫，MSVC `/W4 /WX /permissive-` 與 GCC `-Wall -Wextra` 都要能乾淨編譯。
 *   - 只在 x64 有意義（vr_ipc_abi.h 本身在非 x64 會 #error），所以只在 Windows 程式碼 include。
 */
#pragma once

// standard includes
#include <cstddef>
#include <cstdint>
#include <string>

// local includes
#include "vr_ipc_abi.h"

namespace vripc_abi_table {
  struct row_t {
    const char *key;
    unsigned long long value;
  };

#define VRIPC_ABI_ROW_CONST(c) row_t {"const." #c, static_cast<unsigned long long>(c)}
#define VRIPC_ABI_ROW_SIZE(s) row_t {"size." #s, static_cast<unsigned long long>(sizeof(s))}
#define VRIPC_ABI_ROW_ALIGN(s) row_t {"align." #s, static_cast<unsigned long long>(alignof(s))}
#define VRIPC_ABI_ROW_OFF(s, f) row_t {"off." #s "." #f, static_cast<unsigned long long>(offsetof(s, f))}

  // 機械產生：vr_ipc_abi.h（ABI v1）的 26 個 struct、共 307 列（2026-10-05：config.reserved2 拆出 pose_flags）
  inline constexpr row_t k_rows[] = {
      VRIPC_ABI_ROW_CONST(VRIPC_ABI_VERSION),
      VRIPC_ABI_ROW_CONST(VRIPC_MAGIC_PIPE),
      VRIPC_ABI_ROW_CONST(VRIPC_MAGIC_SHM),
      VRIPC_ABI_ROW_CONST(VRIPC_SHM_SECTION_SIZE),
      VRIPC_ABI_ROW_CONST(VRIPC_PIPE_MAX_MSG),
      VRIPC_ABI_ROW_CONST(VRIPC_TRK_SLOTS),
      VRIPC_ABI_ROW_CONST(VRIPC_FRM_SLOTS),
      VRIPC_ABI_ROW_CONST(VRIPC_TEX_COUNT),
      VRIPC_ABI_ROW_CONST(VRIPC_HAPTIC_SLOTS),
      VRIPC_ABI_ROW_CONST(VRIPC_TIMING_SLOTS),
      VRIPC_ABI_ROW_CONST(VRIPC_LOG_SLOTS),
      VRIPC_ABI_ROW_CONST(VRIPC_LOG_TEXT),
      VRIPC_ABI_ROW_CONST(VRIPC_IFACE_CHARS),
      VRIPC_ABI_ROW_CONST(VRIPC_DXGI_FORMAT_B8G8R8A8_UNORM),
      VRIPC_ABI_ROW_SIZE(vripc_msg_hdr_t),
      VRIPC_ABI_ROW_ALIGN(vripc_msg_hdr_t),
      VRIPC_ABI_ROW_OFF(vripc_msg_hdr_t, magic),
      VRIPC_ABI_ROW_OFF(vripc_msg_hdr_t, type),
      VRIPC_ABI_ROW_OFF(vripc_msg_hdr_t, flags),
      VRIPC_ABI_ROW_OFF(vripc_msg_hdr_t, size),
      VRIPC_ABI_ROW_OFF(vripc_msg_hdr_t, seq),
      VRIPC_ABI_ROW_SIZE(vripc_hello_t),
      VRIPC_ABI_ROW_ALIGN(vripc_hello_t),
      VRIPC_ABI_ROW_OFF(vripc_hello_t, hdr),
      VRIPC_ABI_ROW_OFF(vripc_hello_t, abi_version),
      VRIPC_ABI_ROW_OFF(vripc_hello_t, driver_pid),
      VRIPC_ABI_ROW_OFF(vripc_hello_t, driver_version_packed),
      VRIPC_ABI_ROW_OFF(vripc_hello_t, shm_struct_size),
      VRIPC_ABI_ROW_OFF(vripc_hello_t, reserved_mb),
      VRIPC_ABI_ROW_OFF(vripc_hello_t, driver_caps),
      VRIPC_ABI_ROW_OFF(vripc_hello_t, openvr_sdk_packed),
      VRIPC_ABI_ROW_OFF(vripc_hello_t, iface_directmode),
      VRIPC_ABI_ROW_OFF(vripc_hello_t, reserved),
      VRIPC_ABI_ROW_SIZE(vripc_welcome_t),
      VRIPC_ABI_ROW_ALIGN(vripc_welcome_t),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, hdr),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, abi_version),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, server_pid),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, generation),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, shm_size),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, qpc_frequency),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, adapter_luid_low),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, adapter_luid_high),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, dup_shm_handle),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, dup_evt_trk),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, dup_evt_frm),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, server_version_packed),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, welcome_flags),
      VRIPC_ABI_ROW_OFF(vripc_welcome_t, reserved),
      VRIPC_ABI_ROW_SIZE(vripc_reject_t),
      VRIPC_ABI_ROW_ALIGN(vripc_reject_t),
      VRIPC_ABI_ROW_OFF(vripc_reject_t, hdr),
      VRIPC_ABI_ROW_OFF(vripc_reject_t, reason),
      VRIPC_ABI_ROW_OFF(vripc_reject_t, detail),
      VRIPC_ABI_ROW_SIZE(vripc_textures_t),
      VRIPC_ABI_ROW_ALIGN(vripc_textures_t),
      VRIPC_ABI_ROW_OFF(vripc_textures_t, hdr),
      VRIPC_ABI_ROW_OFF(vripc_textures_t, generation),
      VRIPC_ABI_ROW_OFF(vripc_textures_t, adapter_luid_low),
      VRIPC_ABI_ROW_OFF(vripc_textures_t, adapter_luid_high),
      VRIPC_ABI_ROW_OFF(vripc_textures_t, width),
      VRIPC_ABI_ROW_OFF(vripc_textures_t, height),
      VRIPC_ABI_ROW_OFF(vripc_textures_t, dxgi_format),
      VRIPC_ABI_ROW_OFF(vripc_textures_t, tex_count),
      VRIPC_ABI_ROW_OFF(vripc_textures_t, tex_handle),
      VRIPC_ABI_ROW_OFF(vripc_textures_t, shared_fence_handle),
      VRIPC_ABI_ROW_OFF(vripc_textures_t, consumed_fence_handle),
      VRIPC_ABI_ROW_OFF(vripc_textures_t, shared_fence_initial),
      VRIPC_ABI_ROW_SIZE(vripc_ready_t),
      VRIPC_ABI_ROW_ALIGN(vripc_ready_t),
      VRIPC_ABI_ROW_OFF(vripc_ready_t, hdr),
      VRIPC_ABI_ROW_OFF(vripc_ready_t, generation),
      VRIPC_ABI_ROW_SIZE(vripc_state_t),
      VRIPC_ABI_ROW_ALIGN(vripc_state_t),
      VRIPC_ABI_ROW_OFF(vripc_state_t, hdr),
      VRIPC_ABI_ROW_OFF(vripc_state_t, generation),
      VRIPC_ABI_ROW_OFF(vripc_state_t, kind),
      VRIPC_ABI_ROW_OFF(vripc_state_t, arg),
      VRIPC_ABI_ROW_SIZE(vripc_bye_t),
      VRIPC_ABI_ROW_ALIGN(vripc_bye_t),
      VRIPC_ABI_ROW_OFF(vripc_bye_t, hdr),
      VRIPC_ABI_ROW_OFF(vripc_bye_t, reason),
      VRIPC_ABI_ROW_OFF(vripc_bye_t, detail),
      VRIPC_ABI_ROW_SIZE(vripc_shm_header_t),
      VRIPC_ABI_ROW_ALIGN(vripc_shm_header_t),
      VRIPC_ABI_ROW_OFF(vripc_shm_header_t, magic),
      VRIPC_ABI_ROW_OFF(vripc_shm_header_t, abi_version),
      VRIPC_ABI_ROW_OFF(vripc_shm_header_t, shm_size),
      VRIPC_ABI_ROW_OFF(vripc_shm_header_t, struct_size),
      VRIPC_ABI_ROW_OFF(vripc_shm_header_t, generation),
      VRIPC_ABI_ROW_OFF(vripc_shm_header_t, qpc_frequency),
      VRIPC_ABI_ROW_OFF(vripc_shm_header_t, server_pid),
      VRIPC_ABI_ROW_OFF(vripc_shm_header_t, armed),
      VRIPC_ABI_ROW_OFF(vripc_shm_header_t, server_state),
      VRIPC_ABI_ROW_OFF(vripc_shm_header_t, reserved0),
      VRIPC_ABI_ROW_OFF(vripc_shm_header_t, server_heartbeat_qpc),
      VRIPC_ABI_ROW_OFF(vripc_shm_header_t, reserved1),
      VRIPC_ABI_ROW_SIZE(vripc_driver_status_t),
      VRIPC_ABI_ROW_ALIGN(vripc_driver_status_t),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, generation_ack),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, driver_pid),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, driver_state),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, driver_heartbeat_qpc),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, frames_presented),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, frames_composited),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, drop_noslot),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, drop_acquire_timeout),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, drop_format),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, stale_pose_count),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, outofrange_count),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, posehist_miss),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, last_vsync_qpc),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, swapsets_live),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, last_layer_count),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, space_delta_mdeg),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, other_hmd),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, other_hmd_system),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, act_refresh_mhz),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, act_eye_width),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, act_eye_height),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, act_luid_low),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, act_luid_high),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, degraded_code),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, next_index_calls),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, drop_unknown_layer),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, max_layer_count),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, reserved0),
      VRIPC_ABI_ROW_OFF(vripc_driver_status_t, reserved1),
      VRIPC_ABI_ROW_SIZE(vripc_session_config_t),
      VRIPC_ABI_ROW_ALIGN(vripc_session_config_t),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, eye_width),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, eye_height),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, packed_width),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, packed_height),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, dxgi_format),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, refresh_mhz),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, period_ns),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, fov_tan),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, eye_to_head),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, ipd_m),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, overscan_deg),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, controller_profile),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, vr_caps),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, universe_id),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, adapter_luid_low),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, adapter_luid_high),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, space_epoch),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, layout_epoch),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, dev_arg),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, dev_flags),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, audio_endpoint_id),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, vsync_to_photons_us),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, hmd_extrap_cap_us),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, ctrl_extrap_cap_us),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, stale_oor_ctrl_us),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, stale_zero_vel_us),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, stale_oor_hmd_us),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, pose_flags),
      VRIPC_ABI_ROW_OFF(vripc_session_config_t, reserved2),
      VRIPC_ABI_ROW_SIZE(vripc_pacing_t),
      VRIPC_ABI_ROW_ALIGN(vripc_pacing_t),
      VRIPC_ABI_ROW_OFF(vripc_pacing_t, seq),
      VRIPC_ABI_ROW_OFF(vripc_pacing_t, period_q32),
      VRIPC_ABI_ROW_OFF(vripc_pacing_t, anchor_qpc),
      VRIPC_ABI_ROW_OFF(vripc_pacing_t, slew_ppm_max),
      VRIPC_ABI_ROW_OFF(vripc_pacing_t, pacing_flags),
      VRIPC_ABI_ROW_OFF(vripc_pacing_t, vsync_event_offset_us),
      VRIPC_ABI_ROW_OFF(vripc_pacing_t, mode),
      VRIPC_ABI_ROW_OFF(vripc_pacing_t, epoch),
      VRIPC_ABI_ROW_OFF(vripc_pacing_t, reserved0),
      VRIPC_ABI_ROW_OFF(vripc_pacing_t, reserved1),
      VRIPC_ABI_ROW_OFF(vripc_pacing_t, reserved2),
      VRIPC_ABI_ROW_SIZE(vripc_pose_t),
      VRIPC_ABI_ROW_ALIGN(vripc_pose_t),
      VRIPC_ABI_ROW_OFF(vripc_pose_t, pos),
      VRIPC_ABI_ROW_OFF(vripc_pose_t, rot),
      VRIPC_ABI_ROW_OFF(vripc_pose_t, lin_vel),
      VRIPC_ABI_ROW_OFF(vripc_pose_t, ang_vel),
      VRIPC_ABI_ROW_SIZE(vripc_ctrl_input_t),
      VRIPC_ABI_ROW_ALIGN(vripc_ctrl_input_t),
      VRIPC_ABI_ROW_OFF(vripc_ctrl_input_t, buttons),
      VRIPC_ABI_ROW_OFF(vripc_ctrl_input_t, touches),
      VRIPC_ABI_ROW_OFF(vripc_ctrl_input_t, press_ctr),
      VRIPC_ABI_ROW_OFF(vripc_ctrl_input_t, trigger),
      VRIPC_ABI_ROW_OFF(vripc_ctrl_input_t, grip),
      VRIPC_ABI_ROW_OFF(vripc_ctrl_input_t, stick_x),
      VRIPC_ABI_ROW_OFF(vripc_ctrl_input_t, stick_y),
      VRIPC_ABI_ROW_OFF(vripc_ctrl_input_t, battery),
      VRIPC_ABI_ROW_OFF(vripc_ctrl_input_t, flags),
      VRIPC_ABI_ROW_OFF(vripc_ctrl_input_t, profile),
      VRIPC_ABI_ROW_OFF(vripc_ctrl_input_t, reserved),
      VRIPC_ABI_ROW_SIZE(vripc_tracking_slot_t),
      VRIPC_ABI_ROW_ALIGN(vripc_tracking_slot_t),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, seq),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, sample_id),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, space_epoch),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, flags),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, reserved0),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, sample_time_ns),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, arrival_qpc),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, target_server_qpc),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, predict_ns),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, reserved1),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, pose),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, input),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, reserved2),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, gaze_yaw_f16),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, gaze_pitch_f16),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, gaze_conf),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, gaze_flags),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, reserved3),
      VRIPC_ABI_ROW_OFF(vripc_tracking_slot_t, reserved4),
      VRIPC_ABI_ROW_SIZE(vripc_tracking_ring_t),
      VRIPC_ABI_ROW_ALIGN(vripc_tracking_ring_t),
      VRIPC_ABI_ROW_OFF(vripc_tracking_ring_t, write_index),
      VRIPC_ABI_ROW_OFF(vripc_tracking_ring_t, pad0),
      VRIPC_ABI_ROW_OFF(vripc_tracking_ring_t, slot),
      VRIPC_ABI_ROW_SIZE(vripc_frame_desc_t),
      VRIPC_ABI_ROW_ALIGN(vripc_frame_desc_t),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, seq),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, frame_id),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, generation),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, fence_value),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, tex_idx),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, flags),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, echo_sample_id),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, space_epoch),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, layout_epoch),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, reserved0),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, render_pos),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, render_rot),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, layer_count),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, t_target_qpc),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, present_qpc),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, submit_qpc),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, compose_gpu_us),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, reserved1),
      VRIPC_ABI_ROW_OFF(vripc_frame_desc_t, reserved2),
      VRIPC_ABI_ROW_SIZE(vripc_frame_ring_t),
      VRIPC_ABI_ROW_ALIGN(vripc_frame_ring_t),
      VRIPC_ABI_ROW_OFF(vripc_frame_ring_t, write_index),
      VRIPC_ABI_ROW_OFF(vripc_frame_ring_t, pad0),
      VRIPC_ABI_ROW_OFF(vripc_frame_ring_t, slot),
      VRIPC_ABI_ROW_SIZE(vripc_consume_status_t),
      VRIPC_ABI_ROW_ALIGN(vripc_consume_status_t),
      VRIPC_ABI_ROW_OFF(vripc_consume_status_t, last_consumed_fence),
      VRIPC_ABI_ROW_OFF(vripc_consume_status_t, last_consumed_frame_id),
      VRIPC_ABI_ROW_OFF(vripc_consume_status_t, frames_copied),
      VRIPC_ABI_ROW_OFF(vripc_consume_status_t, frames_skipped_latest),
      VRIPC_ABI_ROW_OFF(vripc_consume_status_t, frames_fence_timeout),
      VRIPC_ABI_ROW_OFF(vripc_consume_status_t, frames_invalid),
      VRIPC_ABI_ROW_OFF(vripc_consume_status_t, frames_device_lost),
      VRIPC_ABI_ROW_OFF(vripc_consume_status_t, reserved),
      VRIPC_ABI_ROW_SIZE(vripc_haptic_evt_t),
      VRIPC_ABI_ROW_ALIGN(vripc_haptic_evt_t),
      VRIPC_ABI_ROW_OFF(vripc_haptic_evt_t, device),
      VRIPC_ABI_ROW_OFF(vripc_haptic_evt_t, duration_us),
      VRIPC_ABI_ROW_OFF(vripc_haptic_evt_t, frequency_hz),
      VRIPC_ABI_ROW_OFF(vripc_haptic_evt_t, amplitude),
      VRIPC_ABI_ROW_OFF(vripc_haptic_evt_t, qpc),
      VRIPC_ABI_ROW_SIZE(vripc_haptic_ring_t),
      VRIPC_ABI_ROW_ALIGN(vripc_haptic_ring_t),
      VRIPC_ABI_ROW_OFF(vripc_haptic_ring_t, head),
      VRIPC_ABI_ROW_OFF(vripc_haptic_ring_t, pad0),
      VRIPC_ABI_ROW_OFF(vripc_haptic_ring_t, tail),
      VRIPC_ABI_ROW_OFF(vripc_haptic_ring_t, pad1),
      VRIPC_ABI_ROW_OFF(vripc_haptic_ring_t, evt),
      VRIPC_ABI_ROW_SIZE(vripc_timing_rec_t),
      VRIPC_ABI_ROW_ALIGN(vripc_timing_rec_t),
      VRIPC_ABI_ROW_OFF(vripc_timing_rec_t, qpc),
      VRIPC_ABI_ROW_OFF(vripc_timing_rec_t, frame_id),
      VRIPC_ABI_ROW_OFF(vripc_timing_rec_t, event),
      VRIPC_ABI_ROW_OFF(vripc_timing_rec_t, flags),
      VRIPC_ABI_ROW_OFF(vripc_timing_rec_t, arg0),
      VRIPC_ABI_ROW_OFF(vripc_timing_rec_t, arg1),
      VRIPC_ABI_ROW_SIZE(vripc_timing_ring_t),
      VRIPC_ABI_ROW_ALIGN(vripc_timing_ring_t),
      VRIPC_ABI_ROW_OFF(vripc_timing_ring_t, head),
      VRIPC_ABI_ROW_OFF(vripc_timing_ring_t, pad0),
      VRIPC_ABI_ROW_OFF(vripc_timing_ring_t, tail),
      VRIPC_ABI_ROW_OFF(vripc_timing_ring_t, pad1),
      VRIPC_ABI_ROW_OFF(vripc_timing_ring_t, rec),
      VRIPC_ABI_ROW_SIZE(vripc_log_line_t),
      VRIPC_ABI_ROW_ALIGN(vripc_log_line_t),
      VRIPC_ABI_ROW_OFF(vripc_log_line_t, qpc),
      VRIPC_ABI_ROW_OFF(vripc_log_line_t, level),
      VRIPC_ABI_ROW_OFF(vripc_log_line_t, len),
      VRIPC_ABI_ROW_OFF(vripc_log_line_t, text),
      VRIPC_ABI_ROW_SIZE(vripc_log_ring_t),
      VRIPC_ABI_ROW_ALIGN(vripc_log_ring_t),
      VRIPC_ABI_ROW_OFF(vripc_log_ring_t, head),
      VRIPC_ABI_ROW_OFF(vripc_log_ring_t, pad0),
      VRIPC_ABI_ROW_OFF(vripc_log_ring_t, tail),
      VRIPC_ABI_ROW_OFF(vripc_log_ring_t, pad1),
      VRIPC_ABI_ROW_OFF(vripc_log_ring_t, line),
      VRIPC_ABI_ROW_SIZE(vripc_shm_t),
      VRIPC_ABI_ROW_ALIGN(vripc_shm_t),
      VRIPC_ABI_ROW_OFF(vripc_shm_t, header),
      VRIPC_ABI_ROW_OFF(vripc_shm_t, driver),
      VRIPC_ABI_ROW_OFF(vripc_shm_t, config),
      VRIPC_ABI_ROW_OFF(vripc_shm_t, pacing),
      VRIPC_ABI_ROW_OFF(vripc_shm_t, tracking),
      VRIPC_ABI_ROW_OFF(vripc_shm_t, frames),
      VRIPC_ABI_ROW_OFF(vripc_shm_t, consume),
      VRIPC_ABI_ROW_OFF(vripc_shm_t, haptic),
      VRIPC_ABI_ROW_OFF(vripc_shm_t, timing),
      VRIPC_ABI_ROW_OFF(vripc_shm_t, log),
  };

#undef VRIPC_ABI_ROW_CONST
#undef VRIPC_ABI_ROW_SIZE
#undef VRIPC_ABI_ROW_ALIGN
#undef VRIPC_ABI_ROW_OFF

  inline constexpr std::size_t k_row_count = sizeof(k_rows) / sizeof(k_rows[0]);

  /// 一列的文字：`<key>=<value>`（不含換行）
  inline std::string format_row(const row_t &row) {
    return std::string(row.key) + "=" + std::to_string(row.value);
  }

  /// 全表的 FNV-1a 64：依序對每列的 `<key>=<value>\n` 取雜湊
  inline std::uint64_t table_digest() {
    std::uint64_t h = 1469598103934665603ull;
    for (const auto &row : k_rows) {
      const std::string line = format_row(row) + "\n";
      for (const unsigned char c : line) {
        h ^= c;
        h *= 1099511628211ull;
      }
    }
    return h;
  }
}  // namespace vripc_abi_table
