---
name: CI
permissions: {}

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  setup_release:
    name: Setup Release
    outputs:
      publish_release: ${{ steps.setup_release.outputs.publish_release }}
      release_body: ${{ steps.setup_release.outputs.release_body }}
      release_commit: ${{ steps.setup_release.outputs.release_commit }}
      release_generate_release_notes: ${{ steps.setup_release.outputs.release_generate_release_notes }}
      release_tag: ${{ steps.setup_release.outputs.release_tag }}
      release_version: ${{ steps.setup_release.outputs.release_version }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup Release
        id: setup_release
        uses: LizardByte/actions/actions/release_setup@70bb8d394d1c92f6113aeec6ae9cc959a5763d15  # v2026.227.200013
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build (${{ matrix.os }} - ${{ matrix.appindicator || 'default' }})
    defaults:
      run:
        shell: ${{ matrix.shell }}
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            shell: "bash"
          - os: ubuntu-latest
            appindicator: "libayatana-appindicator3-dev"
            appindicator_type: "ayatana"
            shell: "bash"
          - os: ubuntu-latest
            appindicator: "libappindicator3-dev"
            appindicator_type: "legacy"
            shell: "bash"
          - os: windows-latest
            shell: "msys2 {0}"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          submodules: recursive

      - name: Setup Dependencies Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ${{ matrix.appindicator }} \
            imagemagick \
            libglib2.0-dev \
            libnotify-dev \
            ninja-build \
            xvfb

      - name: Setup virtual desktop
        if: runner.os == 'Linux'
        uses: LizardByte/actions/actions/virtual_desktop@70bb8d394d1c92f6113aeec6ae9cc959a5763d15  # v2026.227.200013
        with:
          appindicator-version: ${{ matrix.appindicator_type }}
          environment: mate

      - name: Setup Dependencies macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install \
            cmake \
            doxygen \
            graphviz \
            imagemagick \
            ninja \
            node

      - name: Fix macOS screen recording permissions
        if: runner.os == 'macOS'
        run: |
          set -euo pipefail

          configure_system_tccdb() {
            local values=$1
            local dbPath="/Library/Application Support/com.apple.TCC/TCC.db"
            local sqlQuery="INSERT OR IGNORE INTO access VALUES($values);"
            sudo sqlite3 "$dbPath" "$sqlQuery"
          }

          configure_user_tccdb() {
            local values=$1
            local dbPath="$HOME/Library/Application Support/com.apple.TCC/TCC.db"
            local sqlQuery="INSERT OR IGNORE INTO access VALUES($values);"
            sqlite3 "$dbPath" "$sqlQuery"
          }

          systemValuesArray=(
            "'kTCCServiceScreenCapture','/bin/bash',1,2,0,1,NULL,NULL,NULL,'UNUSED',NULL,0,1599831148"
          )
          for values in "${systemValuesArray[@]}"; do
            configure_system_tccdb "$values,NULL,NULL,'UNUSED',${values##*,}"
          done

          userValuesArray=(
            "'kTCCServiceScreenCapture','/bin/bash',1,2,0,1,NULL,NULL,NULL,'UNUSED',NULL,0,1583997993"
          )
          for values in "${userValuesArray[@]}"; do
            configure_user_tccdb "$values,NULL,NULL,'UNUSED',${values##*,}"
          done

          echo "macOS TCC permissions configured."

      - name: Setup Dependencies Windows
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@4f806de0a5a7294ffabaff804b38a9b435a73bda  # v2.30.0
        with:
          msystem: ucrt64
          update: true
          install: >-
            doxygen
            mingw-w64-ucrt-x86_64-binutils
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-graphviz
            mingw-w64-ucrt-x86_64-imagemagick
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-nodejs
            mingw-w64-ucrt-x86_64-toolchain

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.11'

      - name: Python Path
        id: python-path
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            # replace backslashes with double backslashes
            python_path=$(echo "${{ steps.setup-python.outputs.python-path }}" | sed 's/\\/\\\\/g')
          else
            python_path=${{ steps.setup-python.outputs.python-path }}
          fi

          # step output
          echo "python-path=${python_path}"
          echo "python-path=${python_path}" >> "${GITHUB_OUTPUT}"

      - name: Build
        run: |
          mkdir -p build

          if [ "${{ runner.os }}" = "Linux" ]; then
            # Doxygen from Ubuntu is too old, need Doxygen >= 1.10
            DOCS=OFF
          else
            DOCS=ON
          fi

          cmake \
            -DBUILD_DOCS=${DOCS} \
            -DCMAKE_BUILD_TYPE:STRING=Debug \
            -B build \
            -G Ninja \
            -S .
          ninja -C build

      - name: Init tray icon (Windows)
        if: runner.os == 'Windows'
        working-directory: build/tests
        run: ./test_tray --gtest_color=yes --gtest_filter=TrayTest.TestTrayInit

      - name: Configure Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          echo "::group::Enable all tray icons"
          Invoke-WebRequest `
            -Uri "https://raw.githubusercontent.com/paulmann/windows-show-all-tray-icons/main/Enable-AllTrayIcons.ps1" `
            -OutFile "Enable-AllTrayIcons.ps1"
          .\Enable-AllTrayIcons.ps1 -Action Enable -Force  # Enable with comprehensive method (resets ALL icon settings)
          echo "::endgroup::"

          echo "::group::Disable Do Not Disturb"
          Add-Type -AssemblyName System.Windows.Forms
          Start-Process "ms-settings:notifications"
          Start-Sleep -Seconds 2
          [System.Windows.Forms.SendKeys]::SendWait("{TAB}")
          [System.Windows.Forms.SendKeys]::SendWait("{TAB}")
          [System.Windows.Forms.SendKeys]::SendWait(" ")
          echo "::endgroup::"

          echo "::group::Minimize all windows"
          $shell = New-Object -ComObject Shell.Application
          $shell.MinimizeAll()
          echo "::endgroup::"

          echo "::group::Set Date - Hack for Quiet Time"
          $newDate = (Get-Date).AddHours(2)
          Set-Date -Date $newDate
          echo "::endgroup::"

      - name: Run tests
        id: test
        # TODO: tests randomly hang on Linux, https://github.com/LizardByte/tray/issues/45
        timeout-minutes: 3
        working-directory: build/tests
        run: ./test_tray --gtest_color=yes --gtest_output=xml:test_results.xml

      - name: Upload screenshots
        if: >-
          always() &&
          (steps.test.outcome == 'success' || steps.test.outcome == 'failure')
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
        with:
          name: tray-screenshots-${{ runner.os }}${{ matrix.appindicator && format('-{0}', matrix.appindicator) || '' }}
          path: build/tests/screenshots
          if-no-files-found: error

      - name: Generate gcov report
        id: test_report
        # any except canceled or skipped
        if: >-
          always() &&
          (steps.test.outcome == 'success' || steps.test.outcome == 'failure')
        working-directory: build
        run: |
          ${{ steps.python-path.outputs.python-path }} -m pip install gcovr
          ${{ steps.python-path.outputs.python-path }} -m gcovr . -r ../src \
            --exclude-noncode-lines \
            --exclude-throw-branches \
            --exclude-unreachable-branches \
            --verbose \
            --xml-pretty \
            -o coverage.xml

      - name: Debug coverage file
        run: cat build/coverage.xml

      - name: Set codecov flags
        id: codecov_flags
        run: |
          flags="${{ runner.os }}"
          if [ -n "${{ matrix.appindicator }}" ]; then
              flags="${flags},${{ matrix.appindicator }}"
          fi
          echo "flags=${flags}" >> "${GITHUB_OUTPUT}"

      - name: Upload coverage
        # any except canceled or skipped
        if: >-
          always() &&
          steps.test_report.outcome == 'success' &&
          startsWith(github.repository, 'LizardByte/')
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad  # v5.5.3
        with:
          disable_search: true
          fail_ci_if_error: true
          files: ./build/coverage.xml
          flags: "${{ steps.codecov_flags.outputs.flags }}"
          report_type: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload test results
        # any except canceled or skipped
        if: >-
          always() &&
          (steps.test.outcome == 'success' || steps.test.outcome == 'failure') &&
          startsWith(github.repository, 'LizardByte/')
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad  # v5.5.3
        with:
          disable_search: true
          fail_ci_if_error: true
          files: ./build/tests/test_results.xml
          flags: "${{ steps.codecov_flags.outputs.flags }}"
          report_type: test_results
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  release:
    name: Release
    if:
      always() &&
      needs.setup_release.outputs.publish_release == 'true' &&
      needs.build.result == 'success' &&
      startsWith(github.repository, 'LizardByte/')
    needs:
      - build
      - setup_release
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Create/Update GitHub Release
        if: needs.setup_release.outputs.publish_release == 'true'
        uses: LizardByte/actions/actions/release_create@70bb8d394d1c92f6113aeec6ae9cc959a5763d15  # v2026.227.200013
        with:
          allowUpdates: false
          artifacts: ''
          body: ${{ needs.setup_release.outputs.release_body }}
          draft: true
          generateReleaseNotes: ${{ needs.setup_release.outputs.release_generate_release_notes }}
          name: ${{ needs.setup_release.outputs.release_tag }}
          prerelease: true
          tag: ${{ needs.setup_release.outputs.release_tag }}
          token: ${{ secrets.GH_BOT_TOKEN }}
