---
name: CI
permissions: {}

on:
  push:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: write  # needed for setup-release-action
    runs-on: ubuntu-latest
    steps:
      - name: Setup Release
        id: setup-release
        uses: LizardByte/actions/actions/release_setup@70bb8d394d1c92f6113aeec6ae9cc959a5763d15  # v2026.227.200013
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}

      - name: Create Release
        uses: LizardByte/actions/actions/release_create@70bb8d394d1c92f6113aeec6ae9cc959a5763d15  # v2026.227.200013
        with:
          allowUpdates: false
          artifacts: ''
          body: ${{ steps.setup-release.outputs.release_body }}
          draft: true
          generateReleaseNotes: ${{ steps.setup-release.outputs.release_generate_release_notes }}
          name: ${{ steps.setup-release.outputs.release_tag }}
          prerelease: true
          tag: ${{ steps.setup-release.outputs.release_tag }}
          token: ${{ secrets.GH_BOT_TOKEN }}
