/*
 * driver_version.h - VipleStream SteamVR driver version (F10)
 *
 * GENERATED by build-tools/version.ps1 (Propagate-Version) from the
 * repo-root version.json, the single source of truth. Do not edit by
 * hand: every bump / set / propagate rewrites this whole file.
 * Spec: docs/versioning.md section 2.1.
 *
 * Macros:
 *   VIPLE_DRIVER_VERSION_MAJOR / _MINOR / _PATCH
 *       decimal integer literals, e.g. 1 / 5 / 276
 *   VIPLE_DRIVER_VERSION_STR
 *       string literal "MAJOR.MINOR.PATCH", e.g. "1.5.276"
 *   VIPLE_DRIVER_VERSION_RC
 *       four comma-separated fields for .rc FILEVERSION and
 *       PRODUCTVERSION, fourth field always 0, e.g. 1,5,276,0
 *   VIPLE_DRIVER_VERSION_PACKED
 *       32-bit unsigned (MAJOR << 24) | (MINOR << 16) | PATCH for the
 *       IPC handshake driverVer field, e.g. 0x01050114u
 *       (version.ps1 guarantees MAJOR <= 255, MINOR <= 9, PATCH <= 999)
 *
 * ASCII-only on purpose: rc.exe, and cl without /utf-8, read this file
 * with the system ANSI code page; any non-ASCII byte would raise C4819
 * on every include (a hard error under /WX).
 */
#ifndef VIPLE_DRIVER_VERSION_H
#define VIPLE_DRIVER_VERSION_H

#define VIPLE_DRIVER_VERSION_MAJOR 2
#define VIPLE_DRIVER_VERSION_MINOR 0
#define VIPLE_DRIVER_VERSION_PATCH 0
#define VIPLE_DRIVER_VERSION_STR "2.0.0"
#define VIPLE_DRIVER_VERSION_RC 2,0,0,0
#define VIPLE_DRIVER_VERSION_PACKED 0x02000000u

#endif /* VIPLE_DRIVER_VERSION_H */
