#include "autoupdatechecker.h"
#include "version_string.h"  // generated by qmake from version.txt

#include <QNetworkReply>
#include <QJsonDocument>
#include <QJsonArray>
#include <QJsonObject>
#include <QSettings>
#include <QDateTime>

// VIPLE §perf — autoupdate cache window.  GitHub Releases API has a 60
// req/hour unauthenticated rate limit per IP; one request per app launch is
// well within that, but users who restart the app multiple times in a day
// (testing builds, quick reconnects) burn requests for no value.  24h is
// plenty for an "is there a new release" check.
#define AUTOUPDATE_LAST_CHECK_KEY      "autoupdate/lastCheckUnixSec"
#define AUTOUPDATE_CACHE_WINDOW_SEC    (24 * 60 * 60)

AutoUpdateChecker::AutoUpdateChecker(QObject *parent) :
    QObject(parent)
{
    m_Nam = new QNetworkAccessManager(this);

    // Never communicate over HTTP
    m_Nam->setStrictTransportSecurityEnabled(true);

    // Allow HTTP redirects
    m_Nam->setRedirectPolicy(QNetworkRequest::NoLessSafeRedirectPolicy);

    connect(m_Nam, &QNetworkAccessManager::finished,
            this, &AutoUpdateChecker::handleUpdateCheckRequestFinished);

    QString currentVersion(VERSION_STR);
    qDebug() << "Current Moonlight version:" << currentVersion;
    parseStringToVersionQuad(currentVersion, m_CurrentVersionQuad);

    // Should at least have a 1.0-style version number
    Q_ASSERT(m_CurrentVersionQuad.count() > 1);
}

void AutoUpdateChecker::start()
{
    // VipleStream Phase A — query GitHub Releases API for the latest tag
    // and compare with the embedded VERSION_STR.  Replaces the upstream
    // moonlight-stream.org/updates/qt.json check (no longer applicable;
    // VipleStream releases live on the fork's GitHub repo).
    //
    // Endpoint contract (subset we read):
    //   {
    //     "tag_name":  "v1.3.312",            // strip leading 'v'
    //     "html_url":  "https://github.com/.../releases/tag/v1.3.312",
    //     "draft":     false,
    //     "prerelease":false
    //   }
    //
    // Notes:
    //   - We hand the user the release page URL (not the asset download
    //     URL) so they can read the release notes + breaking-change
    //     warnings before grabbing the zip.
    //   - We don't filter `assets[]` per platform — VipleStream's PC
    //     client only ships Windows zips today; if/when other platforms
    //     ship, the matching click goes to the release page anyway.
    //   - GitHub unauthenticated rate limit is 60 req/hour/IP.  One
    //     request per process launch is well within that.
    if (!m_Nam) {
        Q_ASSERT(m_Nam);
        return;
    }

    // VIPLE §perf — skip the GitHub API request if we already checked in the
    // last 24 hours.  Cuts startup latency by ~50-300ms (no DNS + TLS + GET)
    // and keeps us well clear of GitHub's 60 req/hour anonymous rate limit
    // even when the user restarts the app many times a day.  The signal we
    // skip (offering an update prompt) is at most ~24h late, which is fine.
    {
        QSettings settings;
        qint64 lastCheck = settings.value(AUTOUPDATE_LAST_CHECK_KEY, 0).toLongLong();
        qint64 now = QDateTime::currentSecsSinceEpoch();
        if (lastCheck > 0 && now - lastCheck < AUTOUPDATE_CACHE_WINDOW_SEC) {
            qDebug() << "AutoUpdateChecker: skipping (last check"
                     << (now - lastCheck) << "sec ago, cache window"
                     << AUTOUPDATE_CACHE_WINDOW_SEC << "sec)";
            return;
        }
        // Record the attempt now (not after the reply) so a failed/dropped
        // request still respects the cache window — we don't want a flaky
        // network to mean we hammer GitHub on every restart.
        settings.setValue(AUTOUPDATE_LAST_CHECK_KEY, now);
    }

#if QT_VERSION >= QT_VERSION_CHECK(5, 14, 0) && QT_VERSION < QT_VERSION_CHECK(5, 15, 1) && !defined(QT_NO_BEARERMANAGEMENT)
    // HACK: Set network accessibility to work around QTBUG-80947 (introduced in Qt 5.14.0 and fixed in Qt 5.15.1)
    QT_WARNING_PUSH
    QT_WARNING_DISABLE_DEPRECATED
    m_Nam->setNetworkAccessible(QNetworkAccessManager::Accessible);
    QT_WARNING_POP
#endif

    QUrl url("https://api.github.com/repos/finaltwinsen/VipleStream/releases/latest");
    QNetworkRequest request(url);
    // GitHub recommends sending the API version + a JSON Accept header.
    request.setRawHeader("Accept", "application/vnd.github+json");
    request.setRawHeader("X-GitHub-Api-Version", "2022-11-28");
    request.setRawHeader("User-Agent", "VipleStream-Qt-AutoUpdateChecker/1.0");
#if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
    request.setAttribute(QNetworkRequest::Http2AllowedAttribute, true);
#else
    request.setAttribute(QNetworkRequest::HTTP2AllowedAttribute, true);
#endif
    m_Nam->get(request);
}

void AutoUpdateChecker::parseStringToVersionQuad(QString& string, QVector<int>& version)
{
    QStringList list = string.split('.');
    for (const QString& component : std::as_const(list)) {
        version.append(component.toInt());
    }
}

QString AutoUpdateChecker::getPlatform()
{
#if defined(STEAM_LINK)
    return QStringLiteral("steamlink");
#elif defined(APP_IMAGE)
    return QStringLiteral("appimage");
#elif defined(Q_OS_DARWIN) && QT_VERSION >= QT_VERSION_CHECK(6, 0, 0)
    // Qt 6 changed this from 'osx' to 'macos'. Use the old one
    // to be consistent (and not require another entry in the manifest).
    return QStringLiteral("osx");
#else
    return QSysInfo::productType();
#endif
}

int AutoUpdateChecker::compareVersion(QVector<int>& version1, QVector<int>& version2) {
    for (int i = 0;; i++) {
        int v1Val = 0;
        int v2Val = 0;

        // Treat missing decimal places as 0
        if (i < version1.count()) {
            v1Val = version1[i];
        }
        if (i < version2.count()) {
            v2Val = version2[i];
        }
        if (i >= version1.count() && i >= version2.count()) {
            // Equal versions
            return 0;
        }

        if (v1Val < v2Val) {
            return -1;
        }
        else if (v1Val > v2Val) {
            return 1;
        }
    }
}

void AutoUpdateChecker::handleUpdateCheckRequestFinished(QNetworkReply* reply)
{
    Q_ASSERT(reply->isFinished());

    // Delete the QNetworkAccessManager to free resources and
    // prevent the bearer plugin from polling in the background.
    m_Nam->deleteLater();
    m_Nam = nullptr;

    if (reply->error() != QNetworkReply::NoError) {
        // Quiet failure: don't pop a dialog if the user is offline
        // / behind a captive portal / GitHub is rate-limiting us.
        // Logged to qDebug so a developer can grep on demand.
        qDebug() << "[AutoUpdateChecker] HTTP failure (silent):"
                 << reply->errorString();
        reply->deleteLater();
        return;
    }

    QString jsonString;
    {
        QTextStream stream(reply);
#if QT_VERSION >= QT_VERSION_CHECK(6, 0, 0)
        stream.setEncoding(QStringConverter::Utf8);
#else
        stream.setCodec("UTF-8");
#endif
        jsonString = stream.readAll();
    }
    reply->deleteLater();

    QJsonParseError error;
    QJsonDocument jsonDoc = QJsonDocument::fromJson(jsonString.toUtf8(), &error);
    if (jsonDoc.isNull() || !jsonDoc.isObject()) {
        qWarning() << "[AutoUpdateChecker] release JSON malformed:"
                   << error.errorString();
        return;
    }

    QJsonObject release = jsonDoc.object();

    // Skip drafts and pre-releases — they shouldn't ever be returned
    // by /releases/latest, but defensive parse nonetheless.
    if (release.value("draft").toBool(false) ||
            release.value("prerelease").toBool(false)) {
        qDebug() << "[AutoUpdateChecker] latest release flagged draft/prerelease — skip";
        return;
    }

    QString tagName = release.value("tag_name").toString();
    QString releasePageUrl = release.value("html_url").toString();
    if (tagName.isEmpty() || releasePageUrl.isEmpty()) {
        qWarning() << "[AutoUpdateChecker] release JSON missing tag_name or html_url";
        return;
    }

    // GitHub release tags use a leading 'v' (`v1.3.312`); VERSION_STR is
    // `1.3.312`. Strip the prefix before comparing.
    QString latestVersion = tagName;
    if (latestVersion.startsWith(QLatin1Char('v')) || latestVersion.startsWith(QLatin1Char('V'))) {
        latestVersion = latestVersion.mid(1);
    }

    QVector<int> latestVersionQuad;
    parseStringToVersionQuad(latestVersion, latestVersionQuad);
    if (latestVersionQuad.isEmpty()) {
        qWarning() << "[AutoUpdateChecker] tag_name not a version-like string:" << tagName;
        return;
    }

    int res = compareVersion(m_CurrentVersionQuad, latestVersionQuad);
    if (res < 0) {
        qDebug() << "[AutoUpdateChecker] update available — current"
                 << QString(VERSION_STR) << "→ latest" << latestVersion;
        emit onUpdateAvailable(latestVersion, releasePageUrl);
    }
    else if (res > 0) {
        qDebug() << "[AutoUpdateChecker] running ahead of latest release ("
                 << QString(VERSION_STR) << ">" << latestVersion << ") — skip";
    }
    else {
        qDebug() << "[AutoUpdateChecker] up to date (" << latestVersion << ")";
    }
}
